package com.example.demo.MySQL;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/MySQL") // This means URL's start with /demo (after Application path)
public class UserController<UserRepository> {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepositoryInterface userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name,
                       @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        UserModel n = new UserModel();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
        // pasar como parametros y no como json!!!!!!!!!!!!
    }

    @GetMapping("/all")
    public @ResponseBody Iterable<UserModel> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
